### ISSUE TITLE
Feature request: option to disable a rule only for one line

### ISSUE THREAD

**Issue by adrianhurt** [WooodHead/disable-eslint-rule-vscode#1]
First of all, thanks for this simple but useful extension!

I was wondering if it would be possible to add another option at the menu to automatically prepend a `// eslint-disable-next-line [rule]` before the corresponding line.

Thanks!

**Comment by WooodHead** [comment]
Thanks for feedback. Will add this feature.

**Comment by Strajk** [comment]
Switching from Webstorm, I would really appreciate this feature in VSCode

How it looks in Webstorm:
![image](https://user-images.githubusercontent.com/697301/49327131-68929280-f55d-11e8-9d5b-aa66c281d86f.png)

**Comment by Strajk** [comment]
Wait, what... 🤔I just tried hitting `⌘.` in VSCode and the options are there, but I have no idea which extension is adding it :D

![image](https://user-images.githubusercontent.com/697301/49327172-f7071400-f55d-11e8-9626-4711bd6335c4.png)

**Comment by WooodHead** [comment]
Seems to be a vscode builtin feature. Closed
